default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace # 行末の不要な空白を削除
      - id: end-of-file-fixer # ファイルの末尾に改行を保証
      - id: check-docstring-first # ドキュメント文字列が関数定義の直後にあるかを確認
      - id: check-yaml # YAMLファイルの構文エラーをチェック
      - id: detect-private-key # プライベートキーがコミットされていないかをチェック
      - id: check-toml # TOMLファイルの構文エラーをチェック
      - id: check-case-conflict # ファイル名の大文字小文字の競合を検出
      - id: check-added-large-files # 特定のサイズを超える大きなファイルが追加された場合に警告

  # python linter and formatter
  - repo: local # use local ruff
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff-lint
        types_or: [python]
        entry: uv run ruff check . --fix
        language: python

      # Run the formatter.
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format .
        language: python
        types_or: [python]

      # Run the type checker.
      - id: ty-check
        name: ty-check
        entry: uv run ty check
        language: python
        types_or: [python]

  # yaml, json formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml, json]

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--number"] # ファイル内の見出しに番号を自動的に付ける
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          # - mdformat-toc  # 目次を自動生成する
          # - mdformat-black  # コードブロック内のコードをフォーマットする

  # Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args: ["--staged"]  # 変更差分を走査

  # word spelling linter
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.4.1
  #   hooks:
  #     - id: codespell
  #       args:
  #         - --skip=logs/**,data/**,*.ipynb
  #         # - --ignore-words-list=abc,def

  # jupyter notebook cell output clearing
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.8.1
  #   hooks:
  #     - id: nbstripout
